[project]
name = "aiocallback"
dynamic = ["version"]
description = "A library for helping configure asynchronous callbacks using member descriptors"
readme = "README.md"
authors = [{ name = "Vizonex", email="VizonexBusiness@gmail.com" }]
requires-python = ">=3.10"
dependencies = [
    'frozenlist',
    'typing-extensions; python_version<"3.13"',
    "propcache>=0.4.1",
    "freezabledict2>=0.2.0",
    "reductable-params>=1.0.0",
]

keywords=["event callbacks", "callbacks", "asyncio"]
classifiers = [
    "Framework :: AsyncIO",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
[project.urls]
    homepage = "https://github.com/Vizonex/aiocallback"
    repository = "https://github.com/Vizonex/aiocallback.git"

[build-system]
requires = ["setuptools"]

[tool.setuptools.dynamic]
version = {attr = "aiocallback.__version__"}

[tool.ruff]
line-length = 79

[tool.ruff.lint]
extend-select = [
    "I",
    "UP"
]
